version: 2.1
orbs:
  neurio-ecs-orb: cedab734-09b7-11eb-adc1-0242ac120002/neurio-ecs-orb@dev:alpha
#jobs:
#  build:
#    docker:
#      - image: 'circleci/openjdk:11-jdk'
#    steps:
#      - checkout
#      - run:
#          name: Analyze on SonarCloud
#          command: mvn verify sonar:sonar


workflows:
  version: 2.1
  workflow:
    jobs:
      - neurio-ecs-orb/code-analysis:
          name: Static Code Analysis
          context:
            - aws-us-east-1